# Generated by Django 4.2.7 on 2026-07-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='bills/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_emailed', models.BooleanField(default=False)),
                ('emailed_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='trips.trip')),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-generated_at'],
            },
        ),
    ]
